###################################
####### printing commmands   ######
###################################

/geometry/navigator/verbose 0
/material/verbose           0
/vis/verbose                0
/control/verbose            0
/cuts/verbose               0
/particle/verbose           0
/process/verbose            0
/tracking/verbose           0
/hits/verbose               0
/event/verbose              0
/run/verbose                0
/gps/verbose                0
/grdm/verbose               0
